FROM node:18

# Establece el directorio de trabajo en /app
WORKDIR /app

# Copia el package.json y package-lock.json en el contenedor
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto de los archivos en el contenedor
COPY . .

# Construye la aplicación para producción
RUN npm run build

# Expone el puerto
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["npm", "start"]
